### ISSUE TITLE
ZPWR clobbered Debian 12 

### ISSUE THREAD

**Issue by tonywald** [MenkeTechnologies/zpwr#18] opened 2023-10-01 05:22 UTC
**Describe the bug**
On a brand new installation of Debian Bookworm, running `git clone --depth 1 -- https://github.com/MenkeTechnologies/zpwr.git ~/.zpwr && cd ~/.zpwr/install && ./zpwrInstall.sh`, clobbered Xfce. Upon inspection of ~/.zpwr/local/zpwr_log.txt, I see that a number of packages like polkit and systemd were removed automatically during ZPWR install and replaced with sysvinit... 

**To Reproduce**
1. Install Xfce version of Debian Bookworm.
2. Run `git clone --depth 1 -- https://github.com/MenkeTechnologies/zpwr.git ~/.zpwr && cd ~/.zpwr/install && ./zpwrInstall.sh`
3. Follow prompts
4. Installer takes off with downloading deps
5. Come back to a screen full of the same error over and over about running outdated xfce4 package (dont remember the exact name, still trying to find it in logs)
6. Log out, Attempt log back in, freezes after entering password and hitting error
7. Waited for a few hours, no change
8. Force reboot
9. During boot, after "Debian 12" splash screen, black screen, unresponsive pc: Ctrl+Alt+F{1-6} has no reaction and caps lock even doesn't work

**Expected behavior**
A fully functioning ZSH shell in a graphical environment..

**Screenshots**
If you want screenshots as proof sysvinit was installed in place of systemd, I can get them.

**Desktop (please complete the following information):**
 - OS: Debian 12 Bookworm
 - Browser: Firefox
 - Version:Debian:12; Firefox: not sure, but irrelevant

**Additional context**
Bookworm doesn't have an install candidate for mysql-server.. not sure if that matters or not.

**Comment by MenkeTechnologies** [comment] 2023-10-02 01:02
That is weird because I do not install any sys init or systemd related configuration.  Never seen this issue before.  I will try an install with Debian 12.

Debian should be these packages:

```
dependencies_ary=(neovim pkg-config libclang1 clang llvm python3-pip inxi build-essential traceroute proxychains atop tcl mlocate php-bcmath php-mysql php-sockets \
        php-mbstring php-gettext nmon clamav gparted sysstat git reptyr iptraf dstat ecryptfs-utils at netatalk dnsutils ltrace zabbix-agent \
        lua5.1 lua5.1-dev rl-dev software-properties-common afpfs-ng \
        samba samba-common scrot syslog-ng sshfs fuse tomcat8 golang xclip strace \
subversion openssl moreutils cmake tig hexedit boxes tal iperf vim tmux chkrootkit wget cowsay cmatrix htop bpython sl mutt \
    screenfetch ccze htop figlet zsh docker.io docker erlang elixir links \
    rlwrap tor nvm nginx nmap mtr mytop tcpdump redis toilet mysql \
    mongodb postgresql jnettop iotop fping ctags texinfo lsof \
    whois weechat gradle ant maven telnet tree mc ocaml groovy slurm \
    bmon ruby parallel pssh shfmt global python3-dev libssl-dev mysql-server mariadb-server gcc bc lib-gnome2-dev silversearcher-ag libgnomeui-dev libgtk2.0-dev libatk1.0-dev libbonoboui2-dev \
        ncurses-dev libevent-dev libncurses5-dev libcairo2-dev libx11-dev \
        libxpm-dev libxt-dev \
        libperl-dev libpq-dev libpcap-dev fortunes ruby-dev \
        python3-pip libffi-dev libssl-dev grc automake whatweb)
```

**Comment by MenkeTechnologies** [comment] 2023-10-05 20:50
Fixed by removing `sysv-rc-conf`.  Confirmed on Debian 12 install in VM.

<img width="842" alt="Screenshot 2023-10-05 at 5 04 49 PM" src="https://github.com/MenkeTechnologies/zpwr/assets/18195247/1ff6b820-3122-415e-92c1-213efce62d9c">

**Closed as completed** 2023-10-05 21:06 UTC
